Repository phnmnl/container-galaxy-k8s-runtime, pull requests merged in 2018-07, with the labels that each got.

#223 New nmr-integrals tool for NMR spectrum comparison
  config/job_conf.xml
  config/phenomenal_tools2container.yaml
  config/tool_conf.xml
  tools/phenomenal/nmr/nmr-integrals.xml
Labels: Dalcotidine

#233 Upgrade multivariate to 2.3.12
  config/phenomenal_tools2container.yaml
  tools/phenomenal/w4m/multivariate_config.xml
Labels: Dalcotidine, tool update

#234 Upgrade batch correction to 2.2.2
  config/phenomenal_tools2container.yaml
  tools/phenomenal/w4m/batch_correction.xml
Labels: Dalcotidine, tool update

#235 Upgrade quality metrics to 2.2.11
  config/phenomenal_tools2container.yaml
  tools/phenomenal/w4m/qualitymetrics_config.xml
Labels: Dalcotidine, tool update

#230 Upgrade univariate to 2.2.6.
  config/phenomenal_tools2container.yaml
  tools/phenomenal/w4m/univariate_config.xml
Labels: Dalcotidine, tool update

#228 Feature/tool update/mtbls dwnld tmp files in output
  config/phenomenal_tools2container.yaml
  tools/phenomenal/w4m/mtbls-dwnld.xml
Labels: Dalcotidine, tool update

#210 Add Eco-Metabolomics
  config/job_conf.xml
  config/phenomenal_tools2container.yaml
  config/tool_conf.xml
  tools/phenomenal/ecomet/ecomet_01_mtbls_download.xml
  tools/phenomenal/ecomet/ecomet_02a_raw_extract.xml
  tools/phenomenal/ecomet/ecomet_02b_qc_extract.xml
  tools/phenomenal/ecomet/ecomet_03_quality_control.xml
  tools/phenomenal/ecomet/ecomet_04_preparations.xml
  tools/phenomenal/ecomet/ecomet_05a_import_maf.xml
  tools/phenomenal/ecomet/ecomet_05b_peak_picking.xml
  tools/phenomenal/ecomet/ecomet_06_import_traits.xml
  tools/phenomenal/ecomet/ecomet_07_species_diversity.xml
  tools/phenomenal/ecomet/ecomet_08a_species_shannon.xml
  tools/phenomenal/ecomet/ecomet_08b_species_unique.xml
  tools/phenomenal/ecomet/ecomet_08c_species_variability.xml
  tools/phenomenal/ecomet/ecomet_08d_concentration.xml
  tools/phenomenal/ecomet/ecomet_08e_species_features.xml
  tools/phenomenal/ecomet/ecomet_09_species_venn.xml
  tools/phenomenal/ecomet/ecomet_10_species_varpart.xml
  tools/phenomenal/ecomet/ecomet_11_species_nmds.xml
  tools/phenomenal/ecomet/ecomet_12_species_marchantia.xml
  tools/phenomenal/ecomet/ecomet_14_ecology_varpart.xml
  tools/phenomenal/ecomet/ecomet_16_ecology_rda.xml
  tools/phenomenal/ecomet/ecomet_18_phylogeny.xml
  tools/phenomenal/ecomet/ecomet_19a_seasons_shannon.xml
  tools/phenomenal/ecomet/ecomet_19b_seasons_unique.xml
  tools/phenomenal/ecomet/ecomet_19c_seasons_variability.xml
  tools/phenomenal/ecomet/ecomet_19d_seasons_concentration.xml
  tools/phenomenal/ecomet/ecomet_19e_seasons_features.xml
  tools/phenomenal/ecomet/ecomet_23_seasons_rda.xml
  tools/phenomenal/ecomet/ecomet_24_seasons_nmds.xml
  workflows/Galaxy-Workflow-EcoMet.ga
Labels: Dalcotidine

#229 Update XML of isa-extractor tools.
  tools/phenomenal/w4m/isa2mzdata.xml
  tools/phenomenal/w4m/isa2mzml.xml
  tools/phenomenal/w4m/isa2mzxml.xml
  tools/phenomenal/w4m/isa2netcdf.xml
  tools/phenomenal/w4m/isa2nmrml.xml
Labels: Dalcotidine, bug, tool update

#218 updated nmr tools: nmrmlconv, rnmr1d, speaq; removed: nmr soap tools,…
  config/job_conf.xml
  config/phenomenal_tools2container.yaml
  config/tool_conf.xml
  tools/phenomenal/nmr/mtbls2nmrglue.xml
  tools/phenomenal/nmr/mtbls_nmrglue.xml
  tools/phenomenal/nmr/soap_opls.xml
  tools/phenomenal/nmr/soap_process.xml
Labels: Dalcotidine

#239 Upgrade biosigner tool.
  config/phenomenal_tools2container.yaml
  tools/phenomenal/w4m/biosigner_config.xml
Labels: Dalcotidine, tool update

#221 fixed configs
  config/job_conf.xml
  config/phenomenal_tools2container.yaml
  config/tool_conf.xml
  tools/phenomenal/nmr/tamenmr/add_remove_merge.xml
  tools/phenomenal/nmr/tamenmr/alignment.xml
  tools/phenomenal/nmr/tamenmr/anova.xml
  tools/phenomenal/nmr/tamenmr/binning.xml
  tools/phenomenal/nmr/tamenmr/globalAlign.xml
  tools/phenomenal/nmr/tamenmr/import_to_csv.xml
  tools/phenomenal/nmr/tamenmr/import_to_nmrML.xml
  tools/phenomenal/nmr/tamenmr/makeFactorTemplate.xml
  tools/phenomenal/nmr/tamenmr/norm_data.xml
  tools/phenomenal/nmr/tamenmr/normalisation.xml
  tools/phenomenal/nmr/tamenmr/pca.xml
  tools/phenomenal/nmr/tamenmr/peakPicking.xml
  tools/phenomenal/nmr/tamenmr/plotNMR.xml
  tools/phenomenal/nmr/tamenmr/plotNMRSig.xml
  tools/phenomenal/nmr/tamenmr/plsda.xml
  tools/phenomenal/nmr/tamenmr/prepPattern.xml
  tools/phenomenal/nmr/tamenmr/quantilePlot.xml
  tools/phenomenal/nmr/tamenmr/scaling.xml
  tools/phenomenal/nmr/tamenmr/slice.xml
  tools/phenomenal/nmr/tamenmr/transform.xml
  tools/phenomenal/nmr/tamenmr/ttest.xml
Labels: Dalcotidine

#246 Bump version in README to 18.01
  README.md
Labels: Dalcotidine

#250 feature/v18.01 ISA-Tab Viewer plugin
  Dockerfile
  config/plugins/visualizations/isatab-viewer/config/isatab-viewer.xml
  config/plugins/visualizations/isatab-viewer/static/css/ISATabViewer.css
  config/plugins/visualizations/isatab-viewer/static/img/assays/chemistry.svg
  config/plugins/visualizations/isatab-viewer/static/img/assays/metabolite_profiling.svg
  config/plugins/visualizations/isatab-viewer/static/img/assays/proteomics.svg
  config/plugins/visualizations/isatab-viewer/static/img/assays/sequencing.svg
  config/plugins/visualizations/isatab-viewer/static/img/assays/transcriptomics.svg
  config/plugins/visualizations/isatab-viewer/static/js/ISATabViewer.js
  config/plugins/visualizations/isatab-viewer/static/js/handlebars-v1.3.0.js
  config/plugins/visualizations/isatab-viewer/static/js/jquery-1.11.1.min.js
  config/plugins/visualizations/isatab-viewer/templates/isatab-viewer.mako
Labels: Dalcotidine

#253 Add ISA Create Validate Upload workflow
  workflows/Galaxy-Workflow-ISA_Create-Validate-Upload.ga
Labels: Dalcotidine

#254 hotfix/v18.01 ISA Create tour
  config/plugins/tours/create_isa_topdown_tour.yaml
  config/plugins/tours/isacreate_metabo-tour.yaml
Labels: Dalcotidine

#256 Hotfix/ecomet unfound tool
  config/tool_conf.xml
Labels: Dalcotidine, hot-fix

#261 Set container tag for isa-extractor.
  config/phenomenal_tools2container.yaml
Labels: Dalcotidine, hot-fix

#257 Feature/check tools
  .travis.yml
  check_tools
Labels: enhancement

#258 Feature/correct ms-vfetc menu item
  config/job_conf.xml
Labels: Dalcotidine, hot-fix

#262 Hotfix/ecomet isatab
  config/job_conf.xml
  config/phenomenal_tools2container.yaml
  tools/phenomenal/ecomet/ecomet_02b_qc_extract.xml
  workflows/Galaxy-Workflow-EcoMet.ga
Labels: Dalcotidine, hot-fix

#266 fixed consensusXMLToXcms error
  config/job_conf.xml
  config/phenomenal_tools2container.yaml
  tools/phenomenal/ms/convertCAMERAToOpenMS/consensusXMLToXcms.xml
  workflows/Galaxy-Workflow-Metabolomics_LCMS_MS_processing,_quantification,_annotation,_identification_and_statistics.ga
Labels: Dalcotidine, hot-fix

#264 fixed type in tour description
  config/plugins/tours/metfrag+xcms-tour.yaml
Labels: Dalcotidine, hot-fix

#271 new workflow and tool descriptions mzQuality
  tools/phenomenal/ms/mzquality/ms-vfetc.xml
  tools/phenomenal/ms/mzquality/mzquality-blank-effect.xml
  tools/phenomenal/ms/mzquality/mzquality-export-measurements.xml
  tools/phenomenal/ms/mzquality/mzquality-is-rsd.xml
  tools/phenomenal/ms/mzquality/mzquality-plots.xml
  tools/phenomenal/ms/mzquality/mzquality-qc-correction.xml
  tools/phenomenal/ms/mzquality/mzquality-qc-rsd.xml
  tools/phenomenal/ms/mzquality/mzquality-rep-rsd.xml
  tools/phenomenal/ms/mzquality/mzquality-rtshifts.xml
  workflows/Galaxy-Workflow-mzQuality.ga
Labels: Dalcotidine, low priority

#260 upgrades for Isodyn
  config/job_conf.xml
  config/phenomenal_tools2container.yaml
  tools/phenomenal/fluxomics/isodyn/isodyn.xml
Labels: Dalcotidine

#272 hotfix/add missing isa_cvterms
  Dockerfile
  config/galaxy.ini
  config/tool_data_table_conf.xml
  tool-data/isa_cvterms.loc
  tools/phenomenal/isatools/isacreate/isa_cvterms.json
  tools/phenomenal/isatools/isacreate/isa_cvterms.py
  tools/phenomenal/isatools/isacreate/isacreate_metabo.xml
  tools/phenomenal/isatools/isacreate/macros.xml
Labels: Dalcotidine, hot-fix

#274 updated msnbase container version
  config/phenomenal_tools2container.yaml
Labels: Dalcotidine, hot-fix

#273 Correct Sacurine v1 workflow.
  config/phenomenal_tools2container.yaml
  tools/phenomenal/w4m/biosigner_config.xml
  workflows/Galaxy-Workflow-Reconstructed_W4M_sacurine_workflow_(imported_from_API).ga
  workflows/Galaxy-Workflow-w4m_sacurine_v1.ga
Labels: Dalcotidine, hot-fix

#275 Set master tag for biosigner container.
  config/phenomenal_tools2container.yaml
Labels: Dalcotidine, tool update

#278 Update name and description of sacurine v1.
  workflows/Galaxy-Workflow-w4m_sacurine_v1.ga
Labels: Dalcotidine

#277 Update/workflow sacurine v2
  config/phenomenal_tools2container.yaml
  tools/phenomenal/w4m/batch_correction.xml
  workflows/Galaxy-Workflow-w4m_sacurine_v2.ga
Labels: Dalcotidine

#279 Ignore non-tool steps when checking workflows with check-tools script.
  check_tools
Labels: Dalcotidine, enhancement

#276 hotfix/fix assay table rendering in ISA-Tab Viewer plugin
  config/plugins/visualizations/isatab-viewer/static/js/ISATabViewer.js
  config/plugins/visualizations/isatab-viewer/templates/isatab-viewer.mako
Labels: Dalcotidine, hot-fix

#287 Small edits to metfrag tour
  config/plugins/tours/metfrag+xcms-tour.yaml
Labels: Dalcotidine

#283 Integrate latest release of nmr-integrals
  config/phenomenal_tools2container.yaml
  tools/phenomenal/nmr/nmr-integrals.xml
Labels: Dalcotidine

#288 Fix to parameter name in ISA Create that's causing output bug for NMR
  tools/phenomenal/isatools/isacreate/macros.xml
Labels: Dalcotidine, hot-fix

#294 Correct definition of NmrML galaxy datatype
  config/datatypes_conf.xml
  external-datatypes/nmrml_datatype.py
Labels: Dalcotidine

#297 Remove sacurine workflow v1.
  workflows/Galaxy-Workflow-w4m_sacurine_v1.ga
  workflows/Galaxy-Workflow-w4m_sacurine_v2.ga
Labels: Dalcotidine

#298 check_tools script improvements
  .travis.yml
  check_tools
Labels: Dalcotidine

#299 Upgrade version of isa2w4m in XML file.
  tools/phenomenal/w4m/isa2w4m.xml
Labels: Dalcotidine

#303 fixes missing logo #291
  html/partners.png
Labels: Dalcotidine, hot-fix

#304 changed URL to private instance installation
  html/welcome.html
Labels: Dalcotidine, hot-fix

#302 updated metfrag-cli-batch
  config/phenomenal_tools2container.yaml
Labels: Dalcotidine, hot-fix

#300 hotfix/isacreate unbalanced groups
  config/phenomenal_tools2container.yaml
  tools/phenomenal/isatools/isacreate/isacreate_metabo.xml
  tools/phenomenal/isatools/isacreate/macros.xml
Labels: Dalcotidine, hot-fix

#310 added proper logo for UL
  html/partners.png
Labels: Dalcotidine, hot-fix

#295 removed ipo, fixed pwiz
  config/job_conf.xml
  config/phenomenal_tools2container.yaml
  config/tool_conf.xml
  tools/phenomenal/ms/msconvert2.xml
  workflows/Galaxy-Workflow-Metabolomics_LCMS_MS_processing,_quantification,_annotation,_identification_and_statistics.ga
Labels: Dalcotidine, hot-fix, wip

#312 hotfix/isaslicer2 clean
  config/job_conf.xml
  config/phenomenal_tools2container.yaml
  config/tool_conf.xml
  tools/phenomenal/isatools/isaslicer/isa_get_data_files_collection.xml
  tools/phenomenal/isatools/isaslicer/isa_get_data_files_list.xml
  tools/phenomenal/isatools/isaslicer/isa_get_study_factor_values.xml
  tools/phenomenal/isatools/isaslicer/isa_get_study_factors.xml
  tools/phenomenal/isatools/isaslicer2/isaslicer2.xml
  tools/phenomenal/isatools/isaslicer2/isaslicer2_data_filter.xml
Labels: Dalcotidine, hot-fix

#311 Hotfix/pwiz version tag
  config/job_conf.xml
  config/phenomenal_tools2container.yaml
  tools/phenomenal/ms/msconvert2.xml
Labels: Dalcotidine
